# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 16:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recognision.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('xml_file', models.FileField(blank=True, upload_to=recognision.models.algorithm_xml_upload_directory_path)),
                ('type', models.CharField(choices=[('CUSTOM', 'Custom'), ('BASE', 'Base')], max_length=8)),
                ('status', models.CharField(choices=[('IN PROGRESS', 'In progress'), ('DONE', 'Done')], max_length=16)),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('input_image', models.ImageField(upload_to=recognision.models.user_history_directory_path)),
                ('output_image', models.ImageField(blank=True, upload_to=recognision.models.user_history_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('IN PROGRESS', 'In progress'), ('DONE', 'Done')], max_length=16)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognision.Algorithm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, upload_to=recognision.models.image_example_upload_directory_path)),
                ('image_type', models.CharField(choices=[('positive', 'positive'), ('negative', 'negative')], max_length=8)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognision.Algorithm')),
            ],
        ),
    ]
