# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
